version: "3.1"

services:
  lib:
    build:
      context: ./docker
    volumes:
      - ./:/src
      - ${COMPOSER_HOME:-~/.composer}:/.composer
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG:-}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=state-machine}